name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup virtual env
      run: |
        export PYTHON_VERSION=${{ matrix.python-version }}
        export VENV_NAME=zipline-reloaded-venv$PYTHON_VERSION
        virtualenv -p /usr/bin/python$PYTHON_VERSION ~/$VENV_NAME
        source ~/$VENV_NAME/bin/activate
        python -m pip install --upgrade pip
        export PYTHON_LIBS=~/$VENV_NAME/lib/python$PYTHON_VERSION/site-packages
    - name: Install TA lib
      run: |
        cd $PYTHON_LIBS
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar xvfz ta-lib-0.4.0-src.tar.gz
        rm ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure
        make
        sudo make install
    - name: Install TWS api
      run: |
        cd $PYTHON_LIBS
        wget https://interactivebrokers.github.io/downloads/twsapi_macunix.1045.01.zip
        unzip twsapi_macunix.1045.01.zip -d twsapi
        rm twsapi_macunix.1045.01.zip
        cd twsapi/IBJts/source/pythonclient
        pip install wheel
        python setup.py sdist
        python setup.py bdist_wheel
        pip install --upgrade dist/ibapi-10.45.1-py3-none-any.whl
    - name: Install main package and run tests
      run: |
        cd $HOME
        git clone git@github.com:alphaville76/sharadar_db_bundle.git
        cd $HOME/sharadar_db_bundle
        pip install -r requirements.txt
        python setup.py sdist
        python setup.py bdist_wheel
        pip install --upgrade --force-reinstall dist/sharadar_db_bundle-3.0-py3-none-any.whl
        python -m pytest -q
